joint_limits:
  torso_2_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
  torso_3_joint:
#    has_position_limits: true
#    min_position: -3.14
#    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.4
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 5.0
